[book]
authors = ["wukong"]
language = "zh"
multilingual = true
src = "./"
title = "gxl"

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output.html]
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js"]
