[book]
authors = ["wukong"]
language = "zh"
multilingual = true
src = "./"
title = "galaxy-sec operator ecosystem"

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output.html]
additional-css = ["./mermaid.css"]
additional-js = ["./mermaid.min.js"]
